
const KEY='mma_project_s_v8';
let firebaseApp=null, firebaseAuth=null, firebaseDb=null, firebaseFs=null, cloudTimer=null, syncBusy=false;
const base={schemaVersion:18,name:'',level:1,xp:0,rank:'غير مصنف',streak:0,lastDate:null,started:false,profileComplete:false,age:0,height:0,weight:0,sex:'',experience:'',daysPerWeek:0,sessionMin:0,goal:'',equipment:[],preferredSports:[],stats:{striking:0,boxing:0,kickboxing:0,muaythai:0,wrestling:0,bjj:0,grappling:0,mma:0,cardio:0,strength:0,speed:0,footwork:0,fightIQ:0,mobility:0,discipline:0},skills:{jab:0,cross:0,defense:0,combos:0,takedown:0,tddef:0,clinch:0,guard:0,escapes:0,transitions:0},
techniqueMastery:{},
caliMastery:{},
tests:{pushups:0,pullups:0,run:0,plank:0},missions:[],history:[],media:[],injuries:[],achievements:[],bosses:[],sparring:[],sleep:[],nutrition:[],camp:null,events:[],dna:{},coachNotes:[],rankEvaluation:{status:'pending',rating:0,rank:'غير مصنف',confidence:0,videoDate:null,videoType:null,summary:''},readiness:{score:0,date:null},load:{weekly:0,last7:[],lastSession:null},testsAdvanced:{broadJump:0,verticalJump:0,deadHang:0,burpees:0,shuttle:0,sidePlank:0},smartPlan:{date:null,items:[],completed:[]},game:{coins:0,seasonPoints:0,rating:0,division:'غير مصنف',weeklyXP:0,weeklyStart:null,seasonId:null,daily:[],weekly:[],badges:[],claimed:[],shield:1,lastRewardDate:null},settings:{lang:'ar',notifications:false,cloud:false,aiEndpoint:'http://127.0.0.1:8000/analyze',firebase:null}};
let S=Object.assign(structuredClone(base),{});if((S.schemaVersion||0)<18){S=structuredClone(base)}S.stats=Object.assign(base.stats,S.stats||{});S.skills=Object.assign(base.skills,S.skills||{});S.techniqueMastery=Object.assign(base.techniqueMastery,S.techniqueMastery||{});S.caliMastery=Object.assign(base.caliMastery,S.caliMastery||{});S.settings=Object.assign(base.settings,S.settings||{});S.readiness=Object.assign(base.readiness,S.readiness||{});S.load=Object.assign(base.load,S.load||{});S.testsAdvanced=Object.assign(base.testsAdvanced,S.testsAdvanced||{});S.smartPlan=Object.assign(base.smartPlan,S.smartPlan||{});S.game=Object.assign(base.game,S.game||{});let tab='home',LANG='ar',currentUser=null,installPrompt=null;S.settings.lang='ar';S.profileComplete=!!S.profileComplete;
const labels={striking:'الضرب',boxing:'الملاكمة',kickboxing:'الكيك بوكسينغ',muaythai:'مواي تاي',wrestling:'المصارعة',bjj:'الجوجيتسو BJJ',grappling:'الجراپلينغ',mma:'MMA',cardio:'اللياقة',strength:'القوة',speed:'السرعة',footwork:'حركة القدمين',fightIQ:'الذكاء القتالي',mobility:'المرونة والحركة',discipline:'الانضباط'};
const skillNames={jab:'الجاب',cross:'الكروس',defense:'الدفاع',combos:'التركيبات',takedown:'الإسقاطات',tddef:'الدفاع ضد الإسقاط',clinch:'الكلينش',guard:'الحراسة الأرضية',escapes:'الهروب',transitions:'الانتقالات'};
const navs=[['home','⚔️','النظام'],['arena','🏆','الساحة'],['smart','🧭','الخطة الذكية'],['training','🥊','التدريب'],['calisthenics','🤸','الكالستنكس التطوري'],['fitness','💪','اللياقة'],['skills','🌳','شجرة المهارات'],['stats','📊','التحليلات'],['sparring','🥋','السبارينغ'],['progress','🎥','مختبر التطور'],['camp','🏕️','معسكر النزال'],['nutrition','🍗','التغذية'],['recovery','🫀','التعافي'],['ai','🧠','مدرب الذكاء الاصطناعي'],['profile','⚙️','الملف الشخصي']];
const tr={ar:{home:'النظام',training:'التدريب',skills:'شجرة المهارات',stats:'التحليلات',sparring:'السبارينغ',progress:'مختبر التطور',camp:'معسكر النزال',nutrition:'التغذية',recovery:'التعافي',ai:'مدرب الذكاء الاصطناعي',profile:'الملف الشخصي',login:'تسجيل الدخول عبر Google',logout:'تسجيل الخروج'},en:{home:'النظام',training:'التدريب',skills:'شجرة المهارات',stats:'التحليلات',sparring:'السبارينغ',progress:'مختبر التطور',camp:'معسكر النزال',nutrition:'التغذية',recovery:'التعافي',ai:'مدرب الذكاء الاصطناعي',profile:'الملف الشخصي',login:'تسجيل الدخول عبر Google',logout:'تسجيل الخروج'}};
const today=()=>new Date().toISOString().slice(0,10);const save=()=>{localStorage.setItem(KEY,JSON.stringify(S));if(navigator.onLine&&currentUser&&firebaseDb&&!syncBusy){clearTimeout(cloudTimer);cloudTimer=setTimeout(()=>cloudSave(firebaseDb,currentUser.uid),900)}};const t=k=>tr[LANG][k]||k;
function toast(x){let e=document.getElementById('toast');e.textContent=x;e.classList.remove('hidden');setTimeout(()=>e.classList.add('hidden'),2200)}
function need(){return 500+S.level*180}function addXP(n){n=Math.max(0,n);S.xp+=n;if(typeof trackGameXP==='function')trackGameXP(n);while(S.xp>=need()){S.xp-=need();S.level++;toast('⬆️ ارتقاء بالمستوى • '+S.level)}if(typeof checkGameBadges==='function')checkGameBadges();save()}
function nav(){document.getElementById('nav').innerHTML=navs.map(([id,ic,k])=>`<button class="${tab===id?'active':''}" onclick="go('${id}')">${ic} ${t(k)}</button>`).join('')}
function go(x){tab=x;render()}
function generate(){if(S.missions.some(m=>m.date===today()))return;let weak=Object.entries(S.stats).sort((a,b)=>a[1]-b[1]).slice(0,3).map(x=>x[0]);let pool=[['Boxing Skill','20 دقيقة جاب/كروس + دفاع + حركة','boxing',90],['Kickboxing Skill','20 دقيقة ركلات + يدين + حركة','kickboxing',90],['Muay Thai Skill','20 دقيقة Teep + كيك + ركبة/كلينش تقني','muaythai',95],['Wrestling Skill','15 دقيقة stance + level change + sprawl','wrestling',90],['BJJ Skill','20 دقيقة solo drills + guard/escape','bjj',90],['MMA Skill','20 دقيقة مزج ضرب + دخول إسقاط + حركة','mma',100],['كالستنكس Skill','30 دقيقة: الحركة المفتوحة الحالية + تمرينين بناء جسم','strength',110],['Shadow الملاكمة','5 × 3 دقائق • Guard + حركة + تنفس','striking',90],['حركة القدمين Lab','15 دقيقة: دخول/خروج + زوايا','footwork',70],['اللياقة','8 جولات 30ث عمل / 30ث راحة','cardio',80],['القوة الأساس','4×8 Squat + 4×6 Push-up + Pull-up إن أمكن','strength',80],['الحركة والمرونة','12 دقيقة للورك والكاحل والكتف','mobility',50],['الذكاء القتالي','حلّل جولة وسجّل 3 قرارات تكتيكية','fightIQ',50],['الانضباط','حضّر أدواتك + 10 دقائق بلا هاتف','discipline',40],['التعافي Walk','20 دقيقة مشي خفيف + تنفس + ماء','cardio',35]];if(S.injuries.some(x=>!x.cleared))pool=pool.filter(x=>['mobility','fightIQ','discipline','cardio'].includes(x[2]));let chosen=[];weak.forEach(w=>{let x=pool.find(p=>p[2]===w);if(x)chosen.push(x)});pool.sort(()=>Math.random()-.5);pool.forEach(x=>{if(chosen.length<Math.min(6,Math.max(4,S.daysPerWeek+1))&&!chosen.includes(x))chosen.push(x)});S.missions=chosen.map((x,i)=>({id:Date.now()+i,date:today(),title:x[0],desc:x[1],stat:x[2],xp:x[3]+Math.min(50,S.level*2),done:false}));save()}
function complete(id){let m=S.missions.find(x=>x.id===id);if(!m||m.done)return;m.done=true;addXP(m.xp);S.stats[m.stat]=Math.min(100,S.stats[m.stat]+.25);S.history.push({date:today(),type:'quest',name:m.title,xp:m.xp});gameReward('quest',m.xp);if(S.lastDate!==today()){S.streak++;S.lastDate=today()}checkAch();save();render()}
function checkAch(){let c=S.history.filter(x=>x.type==='quest').length;let list=[['q1','أول مهمة',c>=1],['q10','10 المهام',c>=10],['q50','50 المهام',c>=50],['l5','المستوى 5',S.level>=5],['s7','7 اليوم سلسلة',S.streak>=7],['r100','100 التدريب السجلات',S.history.length>=100]];list.forEach(a=>{if(a[2]&&!S.achievements.includes(a[0])){S.achievements.push(a[0]);addXP(150);toast('🏆 '+a[1])}})}
function home(){generate();let pct=Math.round(S.xp/need()*100);let done=S.missions.filter(x=>x.done).length;let weakest=Object.entries(S.stats).sort((a,b)=>a[1]-b[1])[0];document.getElementById('view').innerHTML=`<section class="hero"><div class="card"><div class="eyebrow">نظام المقاتل يعمل</div><h1>${S.name} • المستوى ${S.level}</h1><div class="row"><span class="muted">الرتبة القتالية: ${escapeHtml(S.rank||'غير مصنف')}</span><b>${S.xp} / ${need()} خبرة</b></div><div class="xp"><i style="width:${pct}%"></i></div><div class="grid3"><div><div class="stat">${S.streak}</div><small class="muted">سلسلة</small></div><div><div class="stat">${done}/${S.missions.length}</div><small class="muted">المهام</small></div><div><div class="stat">${Math.round(S.stats[weakest[0]])}</div><small class="muted">الأضعف • ${labels[weakest[0]]}</small></div></div></div><div class="card"><div class="eyebrow">هوية المقاتل</div><div class="big">${S.dna.style||'جاري البناء...'}</div><p class="muted">${S.dna.priority||'كمّل التقييم والتمرين ليبني النظام ملفك.'}</p><button class="btn primary" onclick="openAssessment()">📏 اختبار البداية</button> <button class="btn blue" onclick="ai()">🎥 تقييم الرانك بالفيديو</button></div></section><section class="section card"><div class="row"><h2>🎯 ${LANG==='ar'?'مهام اليوم':'مهام اليوم'}</h2><button class="btn" onclick="S.missions=[];generate();render()">↻ توليد مهام جديدة</button></div>${S.missions.map(m=>`<div class="mission ${m.done?'done':''}" style="padding:10px 0;border-bottom:1px solid var(--line)"><button class="check ${m.done?'done':''}" onclick="complete(${m.id})">${m.done?'✓':''}</button><div><b>${m.title}</b><div class="muted">${m.desc}</div></div><span class="tag">+${m.xp} خبرة</span></div>`).join('')}</section><section class="section grid3"><div class="card"><div class="eyebrow">حدث عشوائي</div><h2>🎲 ${eventOfDay()}</h2><p class="muted">حدث يومي يغيّر طريقة لعبك.</p></div><div class="card boss"><div class="eyebrow">مواجهة الزعيم</div><h2>👹 ${bossName()}</h2><p class="muted">اختبار اختياري • لا تنفذه مع إصابة أو تعب غير طبيعي.</p><button class="btn danger" onclick="bossModal()">ابدأ الزعيم</button></div><div class="card"><div class="eyebrow">اليوم</div><h2>🧠 الأولوية</h2><p>${labels[weakest[0]]}</p><div class="bar"><i style="width:${Math.min(100,S.stats[weakest[0]])}%"></i></div></div></section>`}
function eventOfDay(){let e=['مهمة خبرة مضاعفة','تركيز على حركة القدمين','يوم الذكاء القتالي','مكافأة التعافي','اختبار الانضباط'];return e[new Date().getDay()%e.length]}function bossName(){let w=Object.entries(S.stats).sort((a,b)=>a[1]-b[1])[0][0];return ({cardio:'المحرك الحديدي',wrestling:'جدار الإسقاط',striking:'اختبار الضغط',strength:'القوة Gate',footwork:'صائد الزوايا',grappling:'متاهة الأرض'})[w]||'اختبار المقاتل'}

const CALI=[
 ['push','الدفع','الصدر • الترايسبس • الكتف • قوة الدفع',[['Wall Push-up','دفع على الحائط مع جسم مستقيم.'],['Incline Push-up','دفع مائل بتحكم.'],['Push-up','ضغط كامل بجسم مستقيم.'],['Diamond Push-up','ضغط ضيق مع تحكم كامل.'],['Decline Push-up','القدمين مرتفعتان تدريجياً.'],['Archer Push-up','تحميل أكبر على جهة واحدة.'],['Pseudo Planche Push-up','ميلان للأمام مع كتف قوي.'],['One-Arm Push-up Progression','تدرجات الضغط بيد واحدة.'],['One-Arm Push-up','ضغط بيد واحدة عند جاهزية الجسم.']]],
 ['pull','السحب','الظهر • البايسبس • القبضة',[['Body Row','سحب أفقي على وسيلة ثابتة وآمنة.'],['Negative Pull-up','نزول بطيء وتحكم.'],['Assisted Pull-up','عقلة بمساعدة.'],['Pull-up','عقلة كاملة.'],['Chin-up','عقلة قبضة معكوسة.'],['Archer Pull-up','تحميل أكبر على جهة.'],['L-sit Pull-up','عقلة مع ثبات الرجلين.'],['Muscle-up Progression','تدرجات السحب العالي والانتقال.'],['Muscle-up','انتقال كامل من السحب للدفع.']]],
 ['legs','الرجلين','قوة الرجل الواحدة • التوازن • الانفجار',[['Bodyweight Squat','سكوات كامل بتحكم.'],['Tempo Squat','نزول بطيء وتوقف.'],['Split Squat','تقوية كل رجل.'],['Bulgarian Split Squat','الرجل الخلفية مرتفعة على دعم ثابت.'],['Pistol Progression','تدرجات السكوات على رجل.'],['Pistol Squat','سكوات كامل على رجل واحدة.'],['Shrimp Squat Progression','تدرج متقدم للرجل الواحدة.'],['Nordic Hamstring Progression','تدرج آمن للهامسترنغ.'],['Nordic Curl','قوة متقدمة للهامسترنغ.']]],
 ['core','الكور','البطن • الجذع • الضغط الداخلي',[['Dead Bug','تحكم أساسي بالجذع.'],['Plank','ثبات أمامي.'],['Hollow Hold','وضعية Hollow.'],['Hollow Rock','حركة Hollow بتحكم.'],['Hanging Knee Raise','رفع الركب مع تعليق آمن.'],['L-sit Tuck','ثبات مع الركبتين.'],['L-sit','L-sit كامل تدريجياً.'],['V-sit Progression','رفع أعلى مع تحكم.'],['Dragon Flag Progression','تدرج متقدم.'],['Dragon Flag','Dragon Flag بجودة عالية.']]],
 ['handstand','الوقوف على اليدين','توازن • كتف • رسغ • تحكم',[['Wrist Prep','تجهيز الرسغ والكتف.'],['Crow Stand','توازن أمامي.'],['Tuck Handstand','توازن مقلوب مساعد.'],['Wall Handstand','وقوف على اليدين بالحائط.'],['Chest-to-Wall Handstand','خط جسم أفضل وتحكم.'],['Freestanding Handstand','وقوف حر تدريجياً.'],['Handstand Shoulder Taps','نقل الوزن ببطء.'],['Handstand Push-up Progression','تدرج الضغط على اليدين.'],['Handstand Push-up','ضغط كامل على اليدين.'],['Press to Handstand Progression','تدرج الدخول للوقوف بالضغط.']]],
 ['planche','Planche','كتف • كور • قوة الذراعين • تحكم',[['Planche Lean','ميلان أمامي مضبوط.'],['Tuck Planche Lean','تحميل أكبر مع tuck.'],['Tuck Planche','رفع الجسم في tuck.'],['Advanced Tuck Planche','فتح زاوية الجسم تدريجياً.'],['Straddle Planche Progression','تدرج Straddle.'],['Straddle Planche','ثبات متقدم عند الجاهزية.'],['Planche Push-up Progression','تدرج الضغط في Planche.']]],
 ['lever','Front/Back Lever','سحب مستقيم • كور • لوح الكتف',[['Scapular Pull-up','تحكم بلوح الكتف.'],['Tuck Front Lever','Front Lever بوضع tuck.'],['Advanced Tuck Front Lever','تدرج متقدم.'],['One-leg Front Lever','رجل ممدودة تدريجياً.'],['Front Lever Progression','فتح الجسم تدريجياً.'],['Front Lever','ثبات Front Lever عند الجاهزية.'],['Tuck Back Lever','Back Lever بوضع tuck.'],['Back Lever Progression','تدرج آمن نحو الوضع الكامل.']]],
 ['flag','Human Flag','قبضة • كتف • كور جانبي • تحكم',[['Side Plank','قاعدة للكور الجانبي.'],['Vertical Flag Hold','تدريب الوضع على عمود ثابت وآمن.'],['Tuck Flag','Human Flag بوضع tuck.'],['One-leg Flag','رجل ممدودة تدريجياً.'],['Straddle Flag','تدرج Straddle.'],['Human Flag','ثبات Human Flag عند الجاهزية.']]],
 ['explosive','الانفجار والحركة','سرعة • قفز • قوة انفجارية',[['Squat Jump','قفزة عمودية أساسية.'],['Broad Jump','قفزة أفقية مع هبوط مضبوط.'],['Explosive Push-up','ضغط انفجاري.'],['Clap Push-up','ضغط بتصفيق عند إتقان الأساس.'],['Jumping Lunge','اندفاع انفجاري.'],['Burpee','Burpee مضبوط.'],['Burpee Jump','Burpee بانفجار.'],['Reactive Jump Progression','استجابة سريعة مع هبوط آمن.']]],
 ['grip','القبضة والتعليق','قوة اليد • الساعد • تحمل التعليق',[['Dead Hang','تعليق أساسي.'],['Active Hang','تعليق مع تحكم بالكتف.'],['Towel Hang Progression','تعليق بمنشفة آمنة.'],['Farmer Carry Alternative','حمل آمن حسب المعدات المتاحة.'],['False Grip','قبضة انتقال للـMuscle-up.'],['One-arm Hang Progression','تدرج تعليق جهة واحدة.']]]
];
function caliKey(group,i){return group[0]+'_'+i}
function caliDone(group,i){return (S.caliMastery[caliKey(group,i)]||0)>=5}
function caliUnlocked(group,i){return i===0||caliDone(group,i-1)}
function caliGate(group,i){let v=group[3][i][0];let gates={'Wall Push-up':'10 reps نظيفة','Push-up':'10 reps نظيفة','Pull-up':'5 reps نظيفة','L-sit':'15 ثانية','Freestanding Handstand':'20 ثانية','Handstand Push-up':'3 reps نظيفة','Tuck Planche':'10 ثوانٍ','Advanced Tuck Planche':'8 ثوانٍ','Front Lever':'8 ثوانٍ','Back Lever Progression':'10 ثوانٍ','Human Flag':'5 ثوانٍ','Muscle-up':'3 reps نظيفة','Pistol Squat':'5/رجل'};return gates[v]||'5 حصص بجودة عالية'}
function caliView(){
 let total=CALI.reduce((a,g)=>a+g[3].length,0),done=CALI.reduce((a,g)=>a+g[3].filter((_,i)=>caliDone(g,i)).length,0);
 document.getElementById('view').innerHTML=`<section class="card"><div class="eyebrow">بناء جسم + مهارات</div><h2>🤸 الكالستنكس التطوري</h2><p class="muted">مو مجرد تمارين تكرار: كل حركة لها إتقان تدريجي. عند إكمالها 5 حصص تقنية تُفتح الحركة التالية تلقائياً، ومع كل مستوى تصبح المهارة أصعب.</p><div class="xp"><i style="width:${Math.round(done/total*100)}%"></i></div><div class="row"><span>المهارات المكتملة</span><b>${done} / ${total}</b></div></section>
 <section class="grid2 section">${CALI.map(g=>`<div class="card"><h3>${g[1]}</h3><p class="muted">${g[2]}</p>${g[3].map((v,i)=>{let n=S.caliMastery[caliKey(g,i)]||0,u=caliUnlocked(g,i),d=caliDone(g,i);return `<div class="skill ${!u?'locked':''}"><div class="row"><b>${i+1}. ${v[0]}</b><span class="tag">${d?'✓ مكتملة':u?'مفتوحة':'🔒 مقفلة'}</span></div><p class="muted">${v[1]}</p><div class="bar"><i style="width:${Math.min(100,n/5*100)}%"></i></div><small>${n}/5 حصص إتقان • معيار: ${escapeHtml(caliGate(g,i))}</small>${u&&!d?`<button class="btn blue" style="margin-top:8px" onclick="trainCali('${g[0]}',${i})">تدريب + إتقان</button>`:''}</div>`}).join('')}</div>`).join('')}</section>`;
}
function trainCali(gid,i){let g=CALI.find(x=>x[0]===gid);if(!g||!caliUnlocked(g,i)||caliDone(g,i))return;let x=g[3][i];startTrainingChallenge({sport:'🤸 الكالستنكس',title:'🤸 '+x[0],exercise:x[0],desc:x[1]+' نفّذ الحركة ضمن قدرتك وتوقف عند الألم.',work:x[0].toLowerCase().includes('hold')?20:30,rest:15,rounds:3,mode:'cali',group:g,index:i})}
function showCali(id,i){let g=CALI.find(a=>a[0]===id),v=g[3][i];showModal(`<h2>🤸 ${escapeHtml(v[0])}</h2><p>${escapeHtml(v[1])}</p><div class="card"><h3>🎯 معيار الإتقان</h3><p><b>${escapeHtml(caliGate(g,i))}</b> بدون تدهور واضح في الشكل، مع تحكم بالتنفس والحركة.</p><h3>التدرج</h3><p>لا تنتقل للحركة التالية إلا عندما تتحكم بالحالية. إذا كان الشكل سيئاً أو ظهر ألم، ارجع لدرجة أسهل.</p><ul><li>ابدأ بإحماء الكتفين والرسغين والمفاصل.</li><li>الجودة والتحكم أهم من عدد التكرارات.</li><li>المهارات المتقدمة مثل Handstand وPlanche وLever وHuman Flag تحتاج تدرجات طويلة، وليست قفزة واحدة.</li><li>إذا ظهر ألم حاد أو غير معتاد، أوقف الحركة ولا تحاول تجاوز الألم.</li></ul></div><a class="btn primary" target="_blank" rel="noopener" href="https://www.youtube.com/results?search_query=${encodeURIComponent(v[0]+' calisthenics tutorial progression')}">▶️ شرح وتدرج فيديو</a>`)}
function fitnessView(){let r=readinessScore();document.getElementById('view').innerHTML=`<section class="card"><div class="eyebrow">قدرات اللاعب</div><h2>💪 القوة واللياقة الشاملة</h2><p class="muted">قوة نسبية + انفجار + تحمل هوائي ولاهوائي + كور + قبضة + حركة + توازن + Prehab.</p><div class="grid2"><div class="card"><h3>🏋️ القوة</h3><p>Push/Pull • Squat • Split Squat • Hinge/Nordic • Core</p></div><div class="card"><h3>⚡ الانفجار</h3><p>قفز • ضغط انفجاري • تغيير اتجاه • هبوط مضبوط</p></div><div class="card"><h3>🫁 التحمل</h3><p>قاعدة هوائية + جولات لاهوائية حسب الجاهزية</p></div><div class="card"><h3>🛡️ Prehab</h3><p>كتف • رقبة • ركبة • كاحل • ورك • قبضة</p></div></div><button class="btn primary" onclick="advancedTesting()">📏 اختبار القدرات</button> <button class="btn blue" onclick="go('smart')">🧭 خطتي اليوم</button></section><section class="section card"><h3>جاهزية اليوم: ${r}/100</h3><div class="bar"><i style="width:${r}%"></i></div><p class="muted">القوة وحدها لا تصنع مقاتلاً كاملاً؛ التقنية، التحمل، اتخاذ القرار والتعافي تدخل كلها في التطور.</p></section>`}

const SPORT_CHALLENGES={
 'الملاكمة':[['🥊 الجاب','Jab','اضرب الجاب بسرعة مع رجوع اليد للحماية.',20,10,3],['🥊 الكروس','Cross','ثبّت الوقفة ولف الورك مع الكروس.',20,10,3],['🥊 تركيبات','1-2 Combo','جاب + كروس بتقنية نظيفة.',30,15,3]],
 'الكيك بوكسينغ':[['🦵 الركلة الأمامية','Front Kick','ركلة أمامية مع رجوع سريع للوقفة.',20,10,3],['🦵 Round Kick','Round Kick','دوران الورك والعودة للوقفة.',25,10,3],['🦵 كومبو يد + قدم','Boxing + Kick','تركيبة ضربات ثم ركلة.',30,15,3]],
 'مواي تاي':[['🇹🇭 Teep','Teep','تحكم بالتوازن وعودة الرجل بسرعة.',20,10,3],['🇹🇭 الركبة','Knee','ارفع الركبة بتحكم.',20,10,3],['🇹🇭 كلينش','Clinch','حركة قدم وكلينش تقني بدون قوة زائدة.',30,15,3]],
 'المصارعة':[['🤼 Level Change','Level Change','غيّر المستوى مع ظهر محايد وعودة للوقفة.',20,10,3],['🤼 Sprawl','Sprawl','دافع عن الإسقاط بحركة مسيطَر عليها.',20,15,3],['🤼 Single Leg','Single Leg','تدرّب على الدخول التقني بدون رمي أو ضغط مؤذٍ.',30,15,3]],
 'الجوجيتسو BJJ':[['🥋 Guard','Guard','حافظ على القاعدة والتنفس والسيطرة.',30,15,3],['🥋 Escape','Escape','تدرّب على الهروب التقني ببطء.',30,15,3],['🥋 Guard Pass','Guard Pass','انتقل من السيطرة إلى المرور بتحكم.',30,15,3]],
 'MMA':[['⚔️ إدارة المسافة','Distance','تحرك واضبط المسافة مع حراسة جيدة.',30,15,3],['⚔️ دخول الإسقاط','Takedown Entry','دخول تقني بدون تنفيذ خطر أو إسقاط شريك.',30,15,3],['⚔️ Mix Striking + Grappling','MMA Flow','اربط الضرب بالحركة والجراپلينغ بشكل تقني.',40,20,3]],
 'الكالستنكس':[['🤸 Push-up','Push-up','تكرارات نظيفة مع جسم ثابت.',30,15,3],['🤸 Squat','Squat','نزول وصعود بتحكم كامل.',30,15,3],['🤸 Plank','Plank','ثبات الكور مع تنفس هادئ.',30,15,3]],
 'القوة':[['🏋️ Strength Circuit','Strength','حركة مقاومة آمنة حسب معداتك.',40,20,3]],
 'اللياقة':[['🫁 Conditioning','Conditioning','جهد متدرج بدون تجاوز الجاهزية.',40,20,4]],
 'الحركة والمرونة':[['🧘 Mobility Flow','Mobility','حركات مرونة وتحكم بدون ألم.',45,15,3]],
 'التعافي':[['🫀 Recovery Flow','Recovery','تنفس وحركة خفيفة واستعادة.',60,15,2]]
};
let activeTraining=null,trainingTimer=null;
function training(){document.getElementById('view').innerHTML=`<section class="card exerciseHero"><div class="eyebrow">جلسة تدريب تفاعلية</div><h2>🥊 اختار الرياضة والتحدي</h2><p class="muted">اختار التمرين، ابدأ المؤقت، نفّذ الجولة، وخلي التطبيق يحسب الجولات والـXP والتقدم تلقائياً.</p><div class="grid2"><div class="field"><label>الرياضة</label><select id="lt" onchange="refreshTrainingChallenges()">${Object.keys(SPORT_CHALLENGES).map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>التحدي</label><select id="lc" onchange="updateTrainingPreview()"></select></div></div><div class="grid3"><div class="scorebox"><small>الجولات</small><div class="trainingStat" id="previewRounds">3</div></div><div class="scorebox"><small>عمل</small><div class="trainingStat" id="previewWork">20s</div></div><div class="scorebox"><small>راحة</small><div class="trainingStat" id="previewRest">10s</div></div></div><button class="btn primary" style="margin-top:12px;width:100%" onclick="startSelectedTraining()">🥊 ابدأ التمرين</button><button class="btn gold" style="margin-top:8px;width:100%" onclick="quickChallenge()">⚡ تحدي سريع لأضعف نقطة</button></section><section class="section card"><h3>🧠 كيف تمشي الجلسة؟</h3><p class="muted">تجهيز 5 ثوانٍ → جولة عمل → راحة → الجولة التالية → اكتمال التحدي. كل جولة مكتملة تُحفظ فوراً، وإذا أوقفت الجلسة لا تضيع الجولات السابقة.</p></section>`;refreshTrainingChallenges()}
function refreshTrainingChallenges(){let sport=document.getElementById('lt')?.value,sel=document.getElementById('lc');if(!sel)return;let arr=SPORT_CHALLENGES[sport]||[];sel.innerHTML=arr.map((x,i)=>`<option value="${i}">${x[0]} — ${x[2]}</option>`).join('');updateTrainingPreview()}
function updateTrainingPreview(){let sport=document.getElementById('lt')?.value,i=+(document.getElementById('lc')?.value||0),x=(SPORT_CHALLENGES[sport]||[])[i];if(!x)return;document.getElementById('previewRounds').textContent=x[5];document.getElementById('previewWork').textContent=x[3]+'s';document.getElementById('previewRest').textContent=x[4]+'s'}
function startSelectedTraining(){let sport=document.getElementById('lt')?.value,i=+(document.getElementById('lc')?.value||0),x=(SPORT_CHALLENGES[sport]||[])[i];if(!x)return;startTrainingChallenge({sport,title:x[0],exercise:x[1],desc:x[2],work:x[3],rest:x[4],rounds:x[5],mode:'sport'})}
function startTrainingChallenge(cfg){if(trainingTimer)clearInterval(trainingTimer);activeTraining={...cfg,phase:'ready',remaining:5,roundsDone:0,xp:0,startedAt:Date.now()};renderTrainingModal();trainingTimer=setInterval(tickTraining,1000)}
function tickTraining(){if(!activeTraining)return;activeTraining.remaining--;if(activeTraining.remaining>0){renderTrainingModal();return}if(activeTraining.phase==='ready'){activeTraining.phase='work';activeTraining.remaining=activeTraining.work;renderTrainingModal();return}if(activeTraining.phase==='work'){activeTraining.roundsDone++;activeTraining.xp+=20;addXP(20);S.history.push({date:today(),type:'training_round',name:activeTraining.sport+' • '+activeTraining.exercise+' • الجولة '+activeTraining.roundsDone,xp:20,round:activeTraining.roundsDone});save();if(activeTraining.roundsDone>=activeTraining.rounds){finishTrainingChallenge();return}activeTraining.phase='rest';activeTraining.remaining=activeTraining.rest;renderTrainingModal();return}if(activeTraining.phase==='rest'){activeTraining.phase='work';activeTraining.remaining=activeTraining.work;renderTrainingModal()}}
function renderTrainingModal(){if(!activeTraining)return;let a=activeTraining,phase=a.phase==='ready'?'استعد':a.phase==='work'?'🔥 نفّذ الجولة':'😮‍💨 استراحة';let dots=Array.from({length:a.rounds},(_,i)=>`<span class="roundDot ${i<a.roundsDone?'done':i===a.roundsDone&&a.phase==='work'?'active':''}"></span>`).join('');let sub=a.phase==='ready'?'خذ وضعية البداية':a.phase==='work'?a.desc:'تنفس واستعد للجولة التالية';showModal(`<div class="eyebrow">${escapeHtml(a.sport)}</div><h2>${escapeHtml(a.title)}</h2><p class="muted">${escapeHtml(sub)}</p><div class="roundDots">${dots}</div><div class="timerRing"><div><div class="trainingTimer">${a.remaining}</div><div class="muted">${phase}</div></div></div><div class="grid3"><div class="scorebox"><small>الجولة</small><div class="trainingStat">${Math.min(a.roundsDone+1,a.rounds)}/${a.rounds}</div></div><div class="scorebox"><small>XP الجولات</small><div class="trainingStat">+${a.xp}</div></div><div class="scorebox"><small>الحالة</small><div class="trainingStat" style="font-size:18px">${phase}</div></div></div><button class="btn danger" style="margin-top:12px;width:100%" onclick="stopTrainingChallenge()">إيقاف الجلسة</button>`)}
function finishTrainingChallenge(){let a=activeTraining;if(trainingTimer){clearInterval(trainingTimer);trainingTimer=null}let bonus=60;addXP(bonus);S.history.push({date:today(),type:'training',name:a.sport+' • '+a.exercise,xp:bonus+a.xp,rounds:a.roundsDone,completed:true});if(a.mode==='tech'){let k=techniqueKey(a.group,a.index);S.techniqueMastery[k]=(S.techniqueMastery[k]||0)+1;if(S.techniqueMastery[k]>=5){addXP(120);S.history.push({date:today(),type:'skill_unlock',name:'إتقان '+a.exercise,xp:120})}if(Number.isInteger(a.smartIndex)){let p=ensureSmartPlan();if(!p.completed.includes(a.smartIndex))p.completed.push(a.smartIndex)}}else if(a.mode==='cali'){let k=caliKey(a.group,a.index);S.caliMastery[k]=(S.caliMastery[k]||0)+1;S.stats.strength=Math.min(100,S.stats.strength+.35);S.stats.mobility=Math.min(100,S.stats.mobility+.15);if(S.caliMastery[k]>=5){addXP(100);S.history.push({date:today(),type:'skill_unlock',name:'إتقان '+a.exercise,xp:100})}}else{S.stats[a.sport==='الملاكمة'?'boxing':a.sport==='الكيك بوكسينغ'?'kickboxing':a.sport==='مواي تاي'?'muaythai':a.sport==='المصارعة'?'wrestling':a.sport==='الجوجيتسو BJJ'?'bjj':a.sport==='MMA'?'mma':a.sport==='اللياقة'?'cardio':a.sport==='القوة'||a.sport==='الكالستنكس'?'strength':a.sport==='الحركة والمرونة'?'mobility':'discipline']=Math.min(100,(S.stats[a.sport==='الملاكمة'?'boxing':a.sport==='الكيك بوكسينغ'?'kickboxing':a.sport==='مواي تاي'?'muaythai':a.sport==='المصارعة'?'wrestling':a.sport==='الجوجيتسو BJJ'?'bjj':a.sport==='MMA'?'mma':a.sport==='اللياقة'?'cardio':a.sport==='القوة'||a.sport==='الكالستنكس'?'strength':a.sport==='الحركة والمرونة'?'mobility':'discipline']||5)+.5)}gameReward('challenge',a.xp+bonus);if(S.lastDate!==today()){S.streak++;S.lastDate=today()}checkAch();save();let total=a.xp+bonus;activeTraining=null;showModal(`<h2>🏆 التحدي مكتمل!</h2><p>${escapeHtml(a.title)}</p><div class="grid2"><div class="scorebox"><small>الجولات المكتملة</small><div class="big">${a.roundsDone}/${a.rounds}</div></div><div class="scorebox"><small>المكافأة</small><div class="big">+${total} XP</div></div></div><p class="success">✓ تم حفظ الجولات والتقدم والـXP.</p><button class="btn primary" onclick="closeModal();render()">متابعة</button>`)}
function stopTrainingChallenge(){if(trainingTimer)clearInterval(trainingTimer);trainingTimer=null;let a=activeTraining;activeTraining=null;if(a){save();toast('تم حفظ الجولات المكتملة فقط')}closeModal();render()}

function logSession(){let دقيقة=+document.getElementById('lm').value||0,type=document.getElementById('lt').value,note=document.getElementById('ln').value,xp=Math.min(220,30+Math.round(دقيقة*1.4));addXP(xp);let map={'الملاكمة':'boxing','الكيك بوكسينغ':'kickboxing','مواي تاي':'muaythai','المصارعة':'wrestling','الجوجيتسو BJJ':'bjj','MMA':'mma','الكالستنكس':'strength','القوة':'strength','اللياقة':'cardio','الحركة والمرونة':'mobility','التعافي':'discipline'};S.stats[map[type]]=Math.min(100,S.stats[map[type]]+.7);S.history.push({date:today(),type:'session',name:type,xp,دقيقة,note});save();render();toast('تم التسجيل +'+xp+' خبرة')}
function quickChallenge(){let w=Object.entries(S.stats).sort((a,b)=>a[1]-b[1])[0];showModal(`<h2>⚡ تحدي سريع</h2><p>ركز على أضعف المهارة عندك: <b>${labels[w[0]]}</b></p><p>20 دقيقة تقنية مركزة + 5 دقائق تهدئة.</p><button class="btn primary" onclick="addXP(100);S.history.push({date:today(),type:'challenge',name:'سريع '+labels[w[0]],xp:100});save();closeModal();render()">إكمال +100 خبرة</button>`)}
const SPORT_SKILLS={
 '🥊 الملاكمة':[['stance','الوقفة والحركة'],['jab','الجاب'],['cross','الكروس'],['hook','الهوك'],['uppercut','الأبركت'],['slip','المراوغة'],['roll','الرول'],['parry','الصد'],['combos','التركيبات'],['angles','الزوايا'],['counter','الهجمات المرتدة']],
 '🦵 الكيك بوكسينغ':[['kick','ركلة أمامية'],['round','Round Kick'],['teep','Teep'],['check','صد الركلات'],['knee','ركبة أساسية'],['combokick','تركيبات اليد والقدم'],['switch','Switch Kick'],['lowkick','Low Kick'],['highkick','High Kick']],
 '🇹🇭 مواي تاي':[['stance','وقفة مواي تاي'],['teep','Teep'],['round','Round Kick'],['elbow','الكوع'],['knee','الركبة'],['clinch','كلينش'],['check','Check'],['lowkick','Low Kick'],['elbowcombo','تركيبات الكوع'],['clinchknee','ركب من الكلينش']],
 '🤼 المصارعة':[['stance','Wrestling Stance'],['level','Level Change'],['sprawl','Sprawl'],['single','Single Leg'],['double','Double Leg'],['defense','دفاع الإسقاط'],['scramble','Scramble'],['wall','المصارعة على الحائط'],['chain','ربط الإسقاطات']],
 '🥋 الجوجيتسو BJJ':[['base','Base'],['guard','Guard'],['mount','Mount'],['side','Side Control'],['escape','Escapes'],['sweep','Sweeps'],['pass','Guard Passing'],['back','Back Control'],['submission','Submissions'],['transition','Transitions']],
 '⚔️ MMA':[['stance','MMA Stance'],['distance','إدارة المسافة'],['entry','الدخول للإسقاط'],['cage','Cage Work'],['ground','Ground & Pound تقني'],['wallescape','الهروب من الحائط'],['scramble','Scramble'],['mix','Mixing Striking + Grappling'],['strategy','استراتيجية الجولة']]
};
function techniqueKey(group,i){return group+'_'+i}
function techniqueDone(group,i){return (S.techniqueMastery[techniqueKey(group,i)]||0)>=5}
function techniqueUnlocked(group,i){return i===0||techniqueDone(group,i-1)}
function skills(){
 let groups=Object.entries(SPORT_SKILLS);
 document.getElementById('view').innerHTML=`<section class="card"><div class="eyebrow">شجرة مهارات متعددة الرياضات</div><h2>🌳 MMA Skill Tree</h2><p class="muted">الملاكمة • الكيك بوكسينغ • مواي تاي • المصارعة • BJJ • MMA. كل مهارة تحتاج 5 حصص إتقان، وبعد إكمالها تُفتح المهارة التالية تلقائياً.</p>${groups.map(([g,arr])=>`<div class="section"><h2>${g}</h2><div class="tree">${arr.map((x,i)=>{let n=S.techniqueMastery[techniqueKey(g,i)]||0,d=techniqueDone(g,i),u=techniqueUnlocked(g,i);return `<div class="skill ${!u?'locked':''}"><div class="row"><b>${i+1}. ${x[1]}</b><span class="tag">${d?'✓ إتقان':u?'مفتوحة':'🔒'}</span></div><div class="bar"><i style="width:${Math.min(100,n/5*100)}%"></i></div><small>${n}/5 حصص</small>${u&&!d?`<button class="btn" style="margin-top:7px" onclick="trainTechnique('${escapeHtml(g)}',${i})">🥊 ابدأ التحدي</button>`:''}</div>`}).join('')}</div></div>`).join('')}</section>`;
}
function trainTechnique(group,i){let arr=SPORT_SKILLS[group];if(!arr||!techniqueUnlocked(group,i)||techniqueDone(group,i))return;let x=arr[i];startTrainingChallenge({sport:group,title:'🥋 '+x[1],exercise:x[1],desc:'نفّذ '+x[1]+' بتقنية نظيفة وتحكم. '+(x[0]==='takedown'?'لا تنفذ إسقاطاً على شريك بدون إشراف.':''),work:30,rest:15,rounds:3,mode:'tech',group,index:i})}
function stats(){let rows=Object.entries(S.stats).map(([k,v])=>`<tr><td>${labels[k]}</td><td>${Math.round(v)}</td><td><div class="bar"><i style="width:${v}%"></i></div></td></tr>`).join('');let total=S.history.reduce((a,x)=>a+(x.xp||0),0);document.getElementById('view').innerHTML=`<section class="grid3"><div class="card"><div class="big">${S.level}</div><small class="muted">المستوى</small></div><div class="card"><div class="big">${total}</div><small class="muted">إجمالي الخبرة</small></div><div class="card"><div class="big">${S.history.length}</div><small class="muted">السجلات</small></div></section><section class="section card"><h2>📊 مقاتل التحليلات</h2><table class="table"><tr><th>المهارة</th><th>النتيجة</th><th>التقدم</th></tr>${rows}</table></section><section class="section grid2"><div class="card"><h2>🏆 الإنجازات</h2>${S.achievements.map(x=>`<span class="tag">🏆 ${x}</span>`).join(' ')||'<div class="empty">ابدأ لتفتح الإنجازات.</div>'}</div><div class="card"><h2>🧬 مقاتل DNA</h2><p><b>الأسلوب:</b> ${S.dna.style||'—'}</p><p><b>القوة:</b> ${S.dna.strength||'—'}</p><p><b>نقطة الضعف:</b> ${S.dna.weakness||'—'}</p><p><b>الأولوية:</b> ${S.dna.priority||'—'}</p></div></section>`}
function sparring(){document.getElementById('view').innerHTML=`<section class="card"><div class="eyebrow">سجل السبارينغ</div><h2>🥋 سجّل السبارينغ</h2><div class="grid3"><div class="field"><label>الجولات</label><input id="sr" type="number" value="3"></div><div class="field"><label>مدة الجولة</label><input id="sm" type="number" value="3"></div><div class="field"><label>شدة 1–10</label><input id="si" type="number" min="1" max="10" value="6"></div></div><div class="grid2"><div class="field"><label>شو نجح؟</label><textarea id="sw"></textarea></div><div class="field"><label>شو فشل؟</label><textarea id="sf"></textarea></div></div><div class="field"><label>ملاحظات المدرب</label><textarea id="sc"></textarea></div><button class="btn primary" onclick="saveSparring()">حفظ السبارينغ + تحليل نمط</button></section><section class="section card"><h2>🧠 اكتشاف الأنماط</h2>${sparringPatterns()}</section><section class="section card"><h2>السجل</h2>${S.sparring.slice(-8).reverse().map(x=>`<div style="padding:9px 0;border-bottom:1px solid var(--line)"><b>${x.rounds}×${x.دقيقة}دقيقة</b> • الشدة ${x.intensity}/10<br><span class="success">✓ ${x.good||'—'}</span><br><span class="dangerText">✕ ${x.bad||'—'}</span></div>`).join('')||'<div class="empty">ما في سجلات بعد.</div>'}</section>`}
function saveSparring(){S.sparring.push({date:today(),rounds:+sr.value||3,minutes:+sm.value||3,intensity:+si.value||6,good:sw.value,bad:sf.value,coach:sc.value});addXP(100);S.history.push({date:today(),type:'sparring',name:'السبارينغ Log',xp:100});save();render();toast('🥋 السبارينغ saved')}
function sparringPatterns(){if(!S.sparring.length)return '<div class="muted">بعد عدة سجلات رح يبدأ النظام يلتقط المشاكل المتكررة.</div>';let bad=S.sparring.map(x=>x.bad||'').join(' ').toLowerCase();let hints=[];if(/guard|حارس|ايد|يد/.test(bad))hints.push('استعادة الحراسة يظهر كنمط متكرر.');if(/cardio|نفس|تعب/.test(bad))hints.push('اللياقة/التعب يظهر كنمط متكرر.');if(/takedown|اسقاط|مصارع/.test(bad))hints.push('الدفاع ضد الإسقاط يحتاج أولوية.');return hints.length?hints.map(x=>`<p>⚠️ ${x}</p>`).join(''):'<p>حالياً ما ظهر نمط واضح؛ استمر بالتسجيل.</p>'}
function progress(){document.getElementById('view').innerHTML=`<section class="card"><div class="row"><div><div class="eyebrow">مختبر التطور</div><h2>🎥 خزنة التطور</h2><div class="muted">صور وفيديوهات للمقارنة. الملفات المحلية تبقى على هذا الجهاز.</div></div><button class="btn primary" onclick="document.getElementById('mi').click()">+ الوسائط</button></div><input id="mi" class="hidden" type="file" accept="image/*,video/*" multiple onchange="addMedia(this.files)"></section><section class="section card"><h2>📈 الخط الزمني</h2><div class="timeline">${S.history.slice(-12).reverse().map(x=>`<div><b>${x.name}</b><div class="muted">${x.date} • +${x.xp||0} خبرة</div></div>`).join('')||'<div class="empty">ابدأ التدريب.</div>'}</div></section><section class="section media">${S.media.map((m,i)=>`<div class="card">${m.type.startsWith('image')?`<img src="${m.url}">`:`<video src="${m.url}" controls></video>`}<small class="muted">${m.date}</small><button class="btn danger" onclick="delMedia(${i})">حذف</button></div>`).join('')||'<div class="card empty">أضف أول صورة أو فيديو.</div>'}</section><section class="section card"><h2>🔬 المقارنة</h2><p class="muted">اختَر فيديو/صور لاحقاً لإرسالها إلى مدرب الذكاء الاصطناعي. المقارنة البصرية المتقدمة تحتاج خادم الذكاء الاصطناعي.</p><button class="btn blue" onclick="go('ai')">فتح مدرب الذكاء الاصطناعي</button></section>`}
function addMedia(files){[...files].forEach(f=>{if(f.size>30e6)return toast('الحد 30MB');let r=new FileReader();r.onload=()=>{S.media.push({type:f.type,url:r.result,date:today(),name:f.name});save();render()};r.readAsDataURL(f)})}function delMedia(i){S.media.splice(i,1);save();render()}
function camp(){let c=S.camp;if(!c)document.getElementById('view').innerHTML=`<section class="card"><div class="eyebrow">محرك معسكر النزال</div><h2>🏕️ ابدأ معسكر</h2><div class="grid2"><div class="field"><label>أسابيع</label><input id="cw" type="number" value="8" min="2" max="12"></div><div class="field"><label>الهدف</label><select id="cg"><option>بناء أساس</option><option>تحضير تقني</option><option>رفع اللياقة</option><option>تحضير لنزال مع المدرب</option></select></div></div><button class="btn primary" onclick="startCamp()">ابدأ المعسكر</button></section>`;else document.getElementById('view').innerHTML=`<section class="card"><div class="eyebrow">${c.weeks} أسابيع المعسكر</div><h2>🏕️ الأسبوع ${c.week}/${c.weeks}</h2><div class="bar"><i style="width:${c.week/c.weeks*100}%"></i></div><div class="grid3 section"><div><b>الأساس</b><p class="muted">تقنية + حجم معتدل</p></div><div><b>المرحلة الخاصة</b><p class="muted">سيناريوهات قتال تحت إشراف المدرب</p></div><div><b>التخفيف قبل النزال</b><p class="muted">خفض الحمل قرب النزال</p></div></div><button class="btn primary" onclick="advanceCamp()">إنهاء الأسبوع +250 خبرة</button> <button class="btn danger" onclick="S.camp=null;save();render()">إنهاء المعسكر</button></section>`}
function startCamp(){S.camp={weeks:+cw.value||8,week:1,goal:cg.value};save();render()}function advanceCamp(){if(S.camp.week<S.camp.weeks)S.camp.week++;addXP(250);save();render();toast('🏕️ الأسبوع complete')}
function nutrition(){let n=S.nutrition.at(-1)||{};document.getElementById('view').innerHTML=`<section class="card"><div class="eyebrow">وقود المقاتل</div><h2>🍗 تغذية بسيطة</h2><div class="grid3"><div class="field"><label>الوزن بالكيلوغرام</label><input id="nw" type="number" value="${n.weight||56}"></div><div class="field"><label>الهدف</label><select id="ng"><option>زيادة الوزن</option><option>المحافظة</option><option>خفض الوزن</option></select></div><div class="field"><label>ميزانية اليوم $</label><input id="nb" type="number" value="${n.budget||5}"></div></div><button class="btn primary" onclick="saveFuel()">احسب خطة اليوم</button></section><section class="section grid3"><div class="card"><h2>البروتين</h2><div class="big" id="pr">${Math.round((n.weight||56)*1.7)} غرام</div><small class="muted">تقدير عام</small></div><div class="card"><h2>الماء</h2><div class="big" id="wa">${Math.round((n.weight||56)*35/1000*10)/10} لتر</div></div><div class="card"><h2>أطعمة اقتصادية</h2><p class="muted">بيض • لبن/زبادي • عدس • رز • تونة/دجاج حسب المتاح</p></div></section><section class="section card"><h2>🥗 قاعدة</h2><p class="muted">لا يوجد هنا خفض الوزن قاسٍ أو توصيات طبية. إذا كنت صغير الوزن أو عندك هدف وزن لمنافسة، خليه مع مدرب/مختص.</p></section>`}
function saveFuel(){S.nutrition.push({date:today(),weight:+nw.value||56,budget:+nb.value||5,goal:ng.value});save();render();toast('التغذية plan saved')}
function recovery(){let last=S.sleep.at(-1)||{};let active=S.injuries.filter(x=>!x.cleared);document.getElementById('view').innerHTML=`<section class="card"><div class="eyebrow">محرك التعافي</div><h2>🫀 حالة الجسم</h2><div class="grid3"><div class="field"><label>النوم بالساعات</label><input id="rh" type="number" step="0.1" value="${last.hours||7}"></div><div class="field"><label>الإجهاد 1–10</label><input id="rf" type="number" min="1" max="10" value="${last.fatigue||5}"></div><div class="field"><label>ألم عام 0–10</label><input id="rp" type="number" min="0" max="10" value="${last.pain||0}"></div></div><button class="btn primary" onclick="saveRecovery()">تحديث التعافي</button></section><section class="section card"><h2>التوصية</h2><div class="big">${recoveryScore()} / 100</div><p>${recoveryAdvice()}</p></section><section class="section card"><h2>🩹 الإصابات</h2>${active.map((x,i)=>`<div class="row" style="padding:8px 0;border-bottom:1px solid var(--line)"><span>${x.area} • ${x.pain}/10</span><button class="btn" onclick="clearInjury(${S.injuries.indexOf(x)})">تم التعافي</button></div>`).join('')||'<div class="muted">ما في إصابة مسجلة.</div>'}</section>`}
function recoveryScore(){let n=S.sleep.at(-1);if(!n)return 70;return Math.max(0,Math.min(100,Math.round(100-(n.fatigue*5)-(n.pain*6)+Math.min(20,(n.hours-6)*5))))}function recoveryAdvice(){let s=recoveryScore();if(S.injuries.some(x=>!x.cleared)||s<45)return '🔴 التعافي / modified training. إذا الألم شديد أو غير معتاد، لا تتمرن عليه واطلب تقييماً طبياً.';if(s<70)return '🟡 خفف الحجم وركز على التقنية والنوم.';return '🟢 تدريب كامل مناسب إذا ما عندك أعراض أو إصابات.'}function saveRecovery(){S.sleep.push({date:today(),hours:+rh.value||7,fatigue:+rf.value||5,pain:+rp.value||0});save();render();toast('التعافي updated')}
function ai(){document.getElementById('view').innerHTML=`<section class="card"><div class="eyebrow">عقل المقاتل الذكي</div><h2>🧠 مدرب الذكاء الاصطناعي</h2><p class="muted">ارفع فيديو قصير. الـAI يأخذ لقطات من الفيديو، يحدد أخطاء تقنية قابلة للملاحظة، يعطيك تمارين تصحيح وخطة 7 أيام. مو بديل عن مدرب يشوفك مباشرة.</p><div class="field"><label>نوع الفيديو</label><select id="at"><option>Shadow الملاكمة</option><option>الضرب والتركيبات</option><option>حركة القدمين</option><option>المصارعة</option><option>الجراپلينغ</option><option>اللياقة</option></select></div><input id="av" type="file" accept="video/*"><div class="field"><label>سؤال للمدرب</label><textarea id="aq" placeholder="مثلاً: وين أكبر خطأ عندي؟"></textarea></div><div class="card" style="margin:10px 0"><b>🏅 الرانك القتالي</b><div class="big">${escapeHtml(S.rankEvaluation?.rank||'غير مصنف')}</div><p class="muted">${S.rankEvaluation?.status==='approved'?'تم اعتماد الرانك من تحليل AI.':'غير مصنف — ارفع فيديو أداء حتى يحدد AI تقييمك.'}</p></div><button class="btn primary" onclick="analyzeVideo()">🎥 أرسل الفيديو لتقييم الرانك</button><div id="air" class="section"></div></section><section class="section card"><h2>ملاحظات المدرب</h2>${S.coachNotes.slice(-8).reverse().map(x=>`<div style="padding:8px 0;border-bottom:1px solid var(--line)"><b>${x.date}</b><p>${x.text}</p></div>`).join('')||'<div class="empty">لا توجد ملاحظات.</div>'}</section>`}
function renderAIResult(j){let errors=(j.errors||[]).map((e,i)=>`<div class="card"><div class="row"><b>${i+1}. ${escapeHtml(e.issue||'تصحيح')}</b><span class="tag">${escapeHtml(e.severity||'متوسط')} • ${Math.round((Number(e.confidence)||0)*100)}%</span></div><p>${escapeHtml(e.why_it_matters||'')}</p><p class="warn">🎯 ${escapeHtml(e.cue||'ركز على التحكم وتكرار الحركة بثبات.')}</p></div>`).join('');let drills=(j.drills||[]).map(d=>`<div class="card"><b>🥊 ${escapeHtml(d.name||'تمرين')}</b><div class="muted">${escapeHtml(d.purpose||'')}</div><div>${escapeHtml(d.dose||'3 جولات')}</div><small class="muted">${escapeHtml(d.linked_error||'')}</small></div>`).join('');let plan=(j.seven_day_plan||[]).map((x,i)=>`<div class="scorebox"><b>اليوم ${i+1}</b><div>${escapeHtml(x)}</div></div>`).join('');return `<div class="card"><h3>🧠 ${escapeHtml(j.summary||'تحليل الفيديو')}</h3><p class="muted">التحليل مبني على لقطات من الفيديو؛ زاوية الكاميرا قد تخفي بعض التفاصيل.</p>${j.rank_assessment&&j.rank_assessment.rank?`<hr style="border-color:var(--line)"><h3>🏅 تقييم الرانك</h3><div class="big">${escapeHtml(j.rank_assessment.rank)}</div><p>Rating: <b>${Number(j.rank_assessment.rating)||0}</b> • الثقة: <b>${Math.round((Number(j.rank_assessment.confidence)||0)*100)}%</b></p><p class="muted">${escapeHtml(j.rank_assessment.reason||'')}</p>`:'<p class="warn">⚠️ لم يمنح AI رانك لأن الفيديو غير كافٍ للحكم.</p>'}</div><h3>⚠️ الأخطاء/الملاحظات</h3><div class="grid2">${errors||'<div class="card empty">ما ظهر خطأ واضح يمكن الجزم به من اللقطات.</div>'}</div><h3>🛠️ تمارين التصحيح</h3><div class="grid2">${drills||'<div class="empty">لا توجد تمارين مقترحة.</div>'}</div><h3>📅 خطة 7 أيام</h3><div class="scoregrid">${plan}</div><div class="card dangerbox"><b>🛡️ السلامة:</b> ${escapeHtml(j.safety||'لا تتمرن عبر ألم حاد أو غير معتاد، واستعن بمدرب للفحص المباشر.')}</div>`}
async function analyzeVideo(){let f=document.getElementById('av').files[0];if(!f)return toast('اختر فيديو');if(f.size>40e6)return toast('الفيديو أكبر من 40 ميغابايت');let out=document.getElementById('air');out.innerHTML='<div class="card">⏳ عم حلل الفيديو وأحوّله للقطات... ممكن ياخد شوي.</div>';let endpoint=S.settings.aiEndpoint;if(!endpoint){out.innerHTML='<div class="card airesult">حط رابط خادم الذكاء الاصطناعي من الإعدادات أولاً. ما رح اخترع تحليل من دون AI فعلي.</div>';return}try{let fd=new FormData();fd.append('video',f);fd.append('type',document.getElementById('at').value);fd.append('question',document.getElementById('aq').value);fd.append('mode','rank_assessment');fd.append('profile',JSON.stringify({stats:S.stats,skills:S.skills,dna:S.dna,level:S.level,profile:{age:S.age,height:S.height,weight:S.weight,experience:S.experience,goal:S.goal}}));fd.append('rank_policy','قيّم الأداء المرئي فقط. إذا كانت اللقطات كافية، أعد rank_assessment={rank,rating,confidence,reason}. إذا لم تكن كافية، أعد rank_assessment=null ولا تمنح Rank. لا تعتمد على إدخال اللاعب كناتج مهارة.');let r=await fetch(endpoint,{method:'POST',body:fd});let j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.detail||'خطأ في الخادم');if(j.rank_assessment&&j.rank_assessment.rank){let ra=j.rank_assessment;S.rankEvaluation={status:'approved',rating:Number(ra.rating)||0,rank:String(ra.rank),confidence:Number(ra.confidence)||0,videoDate:today(),videoType:document.getElementById('at').value,summary:String(ra.reason||ra.summary||'')};S.rank=S.rankEvaluation.rank;S.game.rating=S.rankEvaluation.rating;S.game.division=divisionFor(S.game.rating);S.history.push({date:today(),type:'rank_evaluation',name:'AI Rank Evaluation',xp:0,rank:S.rank,rating:S.game.rating});save()}out.innerHTML=renderAIResult(j);S.coachNotes.push({date:today(),text:JSON.stringify(j)});S.history.push({name:'تحليل فيديو بالذكاء الاصطناعي',date:today(),xp:15});S.xp+=15;save();toast('✅ التحليل وصل +15 خبرة')}catch(e){out.innerHTML='<div class="card dangerbox">تعذر تحليل الفيديو: '+escapeHtml(e.message||'خطأ في الخادم')+'<br><small>تأكد أن الخادم شغال وأن الرابط صحيح.</small></div>'}}
function coachBrain(){let e=Object.entries(S.stats).sort((a,b)=>b[1]-a[1]),weak=e[e.length-1],strong=e[0];let style=S.skills.takedown+S.skills.guard>S.skills.jab+S.skills.combos?'متخصص أكثر بالجراپلينغ':'متخصص أكثر بالضرب';S.dna={style, strength:labels[strong[0]]+' • '+Math.round(strong[1]),weakness:labels[weak[0]]+' • '+Math.round(weak[1]),priority:'الأيام السبعة القادمة: '+labels[weak[0]]};save();document.getElementById('air').innerHTML='<div class="card"><h3>عقل المقاتل</h3><p>الأسلوب: <b>'+style+'</b></p><p>القوة: '+labels[strong[0]]+'</p><p>نقطة الضعف: '+labels[weak[0]]+'</p><p>الأولوية: '+labels[weak[0]]+'</p></div>';toast('🧠 DNA updated')}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function profile(){document.getElementById('view').innerHTML=`<section class="card"><h2>⚙️ مقاتل الملف الشخصي</h2><div class="field"><label>اسم اللاعب</label><input id="pn" value="${S.name}"></div><div class="grid2"><div class="field"><label>العمر</label><input id="pa" type="number" min="13" max="100" value="${S.age||21}"></div><div class="field"><label>الطول سم</label><input id="ph" type="number" value="${S.height||175}"></div><div class="field"><label>الوزن كغ</label><input id="pw" type="number" value="${S.weight||70}"></div><div class="field"><label>أيام التدريب</label><input id="pd" type="number" min="1" max="7" value="${S.daysPerWeek}"></div><div class="field"><label>مدة الحصة</label><input id="pm" type="number" min="15" max="240" value="${S.sessionMin}"></div><div class="field"><label>الخبرة</label><select id="pe"><option value="beginner" ${S.experience==='beginner'?'selected':''}>مبتدئ</option><option value="intermediate" ${S.experience==='intermediate'?'selected':''}>متوسط</option><option value="advanced" ${S.experience==='advanced'?'selected':''}>متقدم</option></select></div></div><div class="field"><label>هدفك</label><textarea id="pg">${S.goal}</textarea></div><button class="btn primary" onclick="saveProfile()">حفظ</button> <button class="btn" onclick="notifyMe()">🔔 الإشعارات</button> <button class="btn" onclick="openCloud()">☁️ Google / السحابة</button> <button class="btn blue" onclick="openAISettings()">🤖 خادم الذكاء الاصطناعي</button></section><section class="section card"><h2>🩹 وضع الإصابة</h2><div class="grid2"><div class="field"><label>المنطقة</label><input id="ia" placeholder="مثلاً كتف"></div><div class="field"><label>الألم 0–10</label><input id="ip" type="number" min="0" max="10" value="3"></div></div><button class="btn danger" onclick="addInjury()">تفعيل وضع التعافي</button></section><section class="section card"><h2>💾 البيانات</h2><button class="btn" onclick="exportData()">تصدير نسخة احتياطية</button> <button class="btn" onclick="importData()">استيراد نسخة احتياطية</button> <button class="btn danger" onclick="resetAll()">إعادة ضبط</button></section>`}
function saveProfile(){S.name=pn.value.trim()||'لاعب';S.age=+pa.value||21;S.height=+ph.value||175;S.weight=+pw.value||70;S.daysPerWeek=+pd.value||4;S.sessionMin=+pm.value||60;S.experience=pe.value;S.goal=pg.value.trim()||S.goal;S.profileComplete=true;save();render();toast('تم حفظ الملف')}function addInjury(){let area=ia.value.trim(),pain=+ip.value;if(!area)return toast('اكتب المنطقة');S.injuries.push({area,pain,date:today(),cleared:false});S.missions=[];save();render();toast('التعافي Mode ON')}function clearInjury(i){S.injuries[i].cleared=true;S.missions=[];save();render()}
function openAssessment(){showModal(`<h2>📏 اختبار البداية</h2><p class="muted">هذا الاختبار يبني خط الأساس البدني فقط. لا يعطي Rank ولا Rating. الرانك القتالي يحتاج فيديو وتحليل AI.</p><div class="grid2">${[['pushups','Push-ups'],['pullups','Pull-ups'],['run','1.5km Run (دقيقة)'],['plank','Plank (sec)']].map(x=>`<div class="field"><label>${x[1]}</label><input id="a_${x[0]}" type="number" min=0></div>`).join('')}</div><button class="btn primary" onclick="finishAssessment()">حفظ خط الأساس</button>`)}
function finishAssessment(){let p=+a_pushups.value||0,pu=+a_pullups.value||0,r=+a_run.value||0,pl=+a_plank.value||0;S.tests={pushups:p,pullups:pu,run:r,plank:pl};S.stats.strength=Math.min(100,Math.round(p*.35+pu*.8));S.stats.cardio=Math.min(100,Math.max(0,Math.round(100-Math.max(0,r)*4)));S.stats.discipline=Math.min(100,S.stats.discipline+1);S.history.push({date:today(),type:'test',name:'اختبار خط الأساس',xp:0});save();closeModal();render();toast('📏 تم حفظ خط الأساس — الرانك ما زال بانتظار AI')}
function bossModal(){showModal(`<h2>👹 ${bossName()}</h2><p>اختبار اختياري. لا تعمل Boss إذا عندك إصابة أو التعافي score منخفض.</p><div class="field"><label>نتيجتك %</label><input id="bs" type="number" min="0" max="100" value="70"></div><button class="btn danger" onclick="let s=+bs.value;if(s>=80){addXP(500);toast('👹 BOSS DEFEATED +500 خبرة')}else{addXP(150);toast('صمد الزعيم • +150 خبرة')};S.bosses.push({date:today(),name:bossName(),score:s});save();closeModal();render()">إرسال</button>`)}
function showModal(html){modal.innerHTML=`<div class="card">${html}<div style="margin-top:12px"><button class="btn" onclick="closeModal()">إغلاق</button></div></div>`;modal.classList.remove('hidden')}function closeModal(){modal.classList.add('hidden')}

function openAuth(){showModal(`<h2>🔐 حساب اللاعب</h2><p class="muted">حسابك يحفظ تقدمك على السحابة ويمكنك فتحه من أي جهاز. يمكنك استخدام Google أو البريد الإلكتروني.</p><div class="field"><label>البريد الإلكتروني</label><input id="authEmail" type="email" placeholder="you@example.com"></div><div class="field"><label>كلمة المرور</label><input id="authPass" type="password" minlength="6" placeholder="6 أحرف على الأقل"></div><button class="btn primary" onclick="emailSignIn(false)">دخول</button> <button class="btn green" onclick="emailSignIn(true)">إنشاء حساب</button><button class="btn blue" onclick="googleSignIn()">Google</button><hr><div class="field"><label>إعدادات Firebase (للمطور/النشر)</label><textarea id="fc" placeholder='{"apiKey":"...","authDomain":"...","projectId":"..."}'></textarea></div><button class="btn" onclick="saveFirebase()">حفظ Config</button>`)}
function saveFirebase(){try{S.settings.firebase=JSON.parse(fc.value);save();toast('إعدادات Firebase saved');closeModal()}catch(e){toast('JSON غير صالح')}}
async function initFirebase(){
 if(!S.settings.firebase) throw Error('إعدادات Firebase missing');
 const appmod=await import('https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js');
 const authmod=await import('https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js');
 const fs=await import('https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js');firebaseFs=fs;window.__mmaFS=fs;
 if(!firebaseApp){firebaseApp=appmod.initializeApp(S.settings.firebase,'mma-project-s');firebaseAuth=authmod.getAuth(firebaseApp);firebaseDb=fs.getFirestore(firebaseApp);}
 return {authmod,fs};
}
async function googleSignIn(){
 if(!S.settings.firebase){toast('أضف إعدادات Firebase أولاً');return}
 try{
  const {authmod,fs}=await initFirebase();
  const p=new authmod.GoogleAuthProvider();
  const r=await authmod.signInWithPopup(firebaseAuth,p);currentUser=r.user;
  S.name=r.user.displayName||S.name;S.settings.cloud=true;
  await cloudLoadOrCreate(fs,r.user.uid);save();closeModal();render();toast('☁️ تم ربط Google');
 }catch(e){toast('فشل تسجيل Google: '+e.message)}
}
async function emailSignIn(create){
 if(!S.settings.firebase){toast('أضف إعدادات Firebase أولاً');return}
 try{const {authmod,fs}=await initFirebase();const email=document.getElementById('authEmail').value.trim();const pass=document.getElementById('authPass').value;if(!email||pass.length<6){toast('أدخل بريد صحيح وكلمة مرور 6 أحرف على الأقل');return}const r=create?await authmod.createUserWithEmailAndPassword(firebaseAuth,email,pass):await authmod.signInWithEmailAndPassword(firebaseAuth,email,pass);currentUser=r.user;S.name=r.user.displayName||S.name;S.settings.cloud=true;await cloudLoadOrCreate(fs,r.user.uid);save();closeModal();render();toast(create?'🎉 تم إنشاء الحساب':'☁️ تم تسجيل الدخول')}catch(e){toast('تعذر تسجيل الدخول: '+(e.code||e.message))}}
function openOnboarding(){showModal(`<h2>🥊 أنشئ مقاتلك من الصفر</h2><p class="muted">ما في اسم أو تقييم أو Rank جاهز. أنت بتبني ملفك من الصفر، وبعدها تقييم الرانك القتالي يتم حصراً عبر تحليل فيديو بالذكاء الاصطناعي.</p><div class="grid2"><div class="field"><label>اسم اللاعب</label><input id="obName" placeholder="اكتب اسمك"></div><div class="field"><label>العمر</label><input id="obAge" type="number" min=13 max=100></div><div class="field"><label>الطول (سم)</label><input id="obHeight" type="number" min=100 max=230></div><div class="field"><label>الوزن (كغ)</label><input id="obWeight" type="number" min=30 max=250></div><div class="field"><label>خبرتك</label><select id="obExp"><option value="">اختر</option><option value="beginner">مبتدئ</option><option value="intermediate">متوسط</option><option value="advanced">متقدم</option></select></div><div class="field"><label>أيام التدريب بالأسبوع</label><input id="obDays" type="number" min=1 max=7></div><div class="field"><label>مدة الحصة بالدقائق</label><input id="obMin" type="number" min=10 max=240></div><div class="field"><label>الهدف الرئيسي</label><select id="obGoal"><option value="">اختر</option><option>مقاتل MMA شامل</option><option>قوة وبناء جسم</option><option>مهارات كالستنكس</option><option>لياقة وخسارة دهون</option><option>تحضير لنزال</option></select></div></div><button class="btn primary" onclick="finishOnboarding()">🚀 ابدأ من الصفر</button>`)}
function finishOnboarding(){let name=obName.value.trim();if(!name||!obAge.value||!obHeight.value||!obWeight.value||!obExp.value||!obDays.value||!obMin.value||!obGoal.value)return toast('كمّل معلوماتك كلها أولاً');S.name=name;S.age=+obAge.value;S.height=+obHeight.value;S.weight=+obWeight.value;S.experience=obExp.value;S.daysPerWeek=+obDays.value;S.sessionMin=+obMin.value;S.goal=obGoal.value;S.profileComplete=true;S.started=true;S.rank='غير مصنف';S.rankEvaluation={status:'pending',rating:0,rank:'غير مصنف',confidence:0,videoDate:null,videoType:null,summary:''};S.stats=Object.fromEntries(Object.keys(base.stats).map(k=>[k,0]));S.skills=Object.fromEntries(Object.keys(base.skills).map(k=>[k,0]));S.game=structuredClone(base.game);S.smartPlan={date:null,items:[],completed:[]};S.missions=[];save();closeModal();generate();render();toast('🔥 تم إنشاء مقاتلك من الصفر')}
async function cloudLoadOrCreate(fs,uid){
 try{
  const {doc,getDoc}=fs; const ref=doc(firebaseDb,'fighters',uid); const snap=await getDoc(ref);
  if(snap.exists()){
   const remote=snap.data();
   const keep={...S.settings};
   if(Number(remote.schemaVersion||0)<18){S=structuredClone(base);S.settings=Object.assign(base.settings,keep);await cloudSave(firebaseDb,uid);toast('☁️ تم بدء ملفك من الصفر وفق النظام الجديد');return}
   S=Object.assign(structuredClone(base),remote);S.settings=Object.assign(base.settings,S.settings||{},keep);save();toast('☁️ التقدم loaded');
  } else await cloudSave(firebaseDb,uid);
 }catch(e){toast('فشل تحميل السحابة')}
}
async function cloudSave(db,uid){
 if(syncBusy)return; syncBusy=true;
 try{
  const {doc,setDoc}=await import('https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js');
  const payload=JSON.parse(JSON.stringify(S));payload.schemaVersion=18;payload._meta={updatedAt:new Date().toISOString(),appVersion:'V18.0'};
  await setDoc(doc(db,'fighters',uid),payload,{merge:true});
 }catch(e){toast('فشل حفظ السحابة')}finally{syncBusy=false}
}
async function cloudLogout(){try{if(firebaseAuth){const {signOut}=await import('https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js');await signOut(firebaseAuth)}}catch(e){}currentUser=null;S.settings.cloud=false;save();render();toast('Signed out')}
function openCloud(){showModal(`<h2>☁️ Google / السحابة</h2><p class="muted">سجّل الدخول ليتم تحميل تقدمك تلقائياً وحفظه بعد كل تغيير تقريباً. أنشئ تطبيق Firebase للويب وفعّل Google Sign-in وFirestore.</p><div class="field"><label>إعدادات Firebase JSON</label><textarea id="fcp">${S.settings.firebase?escapeHtml(JSON.stringify(S.settings.firebase)):''}</textarea></div><button class="btn primary" onclick="try{S.settings.firebase=JSON.parse(fcp.value);save();toast('حفظd');closeModal()}catch(e){toast('بيانات JSON غير صالحة')}">حفظ Config</button> <button class="btn" onclick="googleSignIn()">تسجيل الدخول عبر Google</button> ${currentUser?'<button class="btn danger" onclick="cloudLogout()">تسجيل الخروج</button>':''}</div>`)}
function openAISettings(){showModal(`<h2>🤖 خادم الذكاء الاصطناعي</h2><p class="muted">ضع رابط الخادم آمن. لا تضع مفتاح API داخل التطبيق.</p><div class="field"><label>الرابط</label><input id="aie" value="${S.settings.aiEndpoint||''}" placeholder="https://your-domain/analyze"></div><button class="btn primary" onclick="S.settings.aiEndpoint=aie.value.trim();save();closeModal();toast('AI endpoint saved')">حفظ</button>`)}
async function notifyMe(){if(!('Notification'in window))return toast('غير مدعوم');let p=await Notification.requestPermission();S.settings.notifications=p==='granted';save();if(p==='granted')new Notification('نظام MMA',{body:'مهمة system متصل ⚔️'});toast(p==='granted'?'الإشعارات ON':'تم رفض الإذن')}
function exportData(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(S,null,2)],{type:'application/json'}));a.download='mma-project-s-backup.json';a.click()}function importData(){let i=document.createElement('input');i.type='file';i.accept='.json';i.onchange=()=>{let r=new FileReader();r.onload=()=>{try{S=Object.assign(structuredClone(base),JSON.parse(r.result));save();render();toast('تم الاستيراد')}catch(e){toast('النسخة الاحتياطية غير صالحة')}};r.readAsText(i.files[0])};i.click()}function resetAll(){if(confirm('حذف كل التقدم المحلي?')){localStorage.removeItem(KEY);location.reload()}}
function toggleLang(){LANG='ar';S.settings.lang='ar';S.profileComplete=!!S.profileComplete;save();document.documentElement.lang='ar';document.documentElement.dir='rtl';render()}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;document.getElementById('installBtn')?.classList.remove('hidden')});
async function installApp(){if(!installPrompt){toast('من قائمة المتصفح اختَر «تثبيت التطبيق» أو «إضافة إلى الشاشة الرئيسية»');return}installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;document.getElementById('installBtn')?.classList.add('hidden')}

const SMART_SKILL_LANES=[
 {name:'🥊 الملاكمة',key:'boxing'}, {name:'🦵 الكيك بوكسينغ',key:'kickboxing'}, {name:'🇹🇭 مواي تاي',key:'muaythai'}, {name:'🤼 المصارعة',key:'wrestling'}, {name:'🥋 BJJ',key:'bjj'}, {name:'⚔️ MMA',key:'mma'}
];
function readinessScore(){let n=S.sleep.at(-1);if(!n)return S.readiness.score||70;let r=100-(n.fatigue*5)-(n.pain*7)+Math.min(20,(n.hours-7)*6);if(S.injuries.some(x=>!x.cleared))r-=20;return Math.max(0,Math.min(100,Math.round(r)))}
function trainingMode(){let r=readinessScore(),since=Date.now()-7*86400000,recent=(S.history||[]).filter(x=>x.date&&new Date(x.date).getTime()>=since&&['session','technique','calisthenics','smart'].includes(x.type)).length;if(S.injuries.some(x=>!x.cleared)||r<40)return 'recovery';if(recent>=Math.max(4,S.daysPerWeek+1))return 'light';return r<60?'light':r<80?'normal':'hard'}
function currentCali(){for(const g of CALI){for(let i=0;i<g[3].length;i++){if(caliUnlocked(g,i)&&!caliDone(g,i))return {g,i,v:g[3][i]}}}return null}
function nextSportSkill(groupName){let group=Object.keys(SPORT_SKILLS).find(g=>g.includes(groupName));if(!group)return null;let arr=SPORT_SKILLS[group];for(let i=0;i<arr.length;i++){if(techniqueUnlocked(group,i)&&!techniqueDone(group,i))return {group,i,name:arr[i][1]}}return null}
function buildSmartPlan(){let mode=trainingMode(),r=readinessScore(),items=[],lanes=SMART_SKILL_LANES.slice().sort((a,b)=>(S.stats[a.key]||5)-(S.stats[b.key]||5));
 if(mode==='recovery')items=[{icon:'🫀',title:'Recovery Session',desc:'20–35 دقيقة مشي خفيف + تنفس + Mobility لطيف',type:'recovery',xp:35},{icon:'🧠',title:'مراجعة ذهنية',desc:'10 دقائق تصور تقني بدون إجهاد',type:'iq',xp:25}];
 else {for(const lane of lanes.slice(0,2)){let a=nextSportSkill(lane.name);if(a)items.push({icon:'🎯',title:lane.name+' • '+a.name,desc:'20–35 دقيقة تقنية بجودة عالية',type:'tech',group:a.group,index:a.i,xp:70})}let cal=currentCali();if(cal)items.push({icon:'🤸',title:'كالستنكس • '+cal.v[0],desc:'20–30 دقيقة تدرج مهارة + تمارين مساعدة لبناء الجسم',type:'cali',group:cal.g[0],index:cal.i,xp:70});items.push({icon:'🫁',title:'Conditioning',desc:mode==='hard'?'8–12 جولة قصيرة مع راحة كافية':'6–8 جولات معتدلة بدون إنهاك',type:'conditioning',xp:55});items.push({icon:'🧘',title:'Mobility + Prehab',desc:'10–15 دقيقة للكتف والورك والكاحل والعمود الفقري',type:'mobility',xp:35});if(mode==='hard')items.push({icon:'🧠',title:'Fight IQ',desc:'10 دقائق تحليل جولة أو تصور مواقف وقرارات',type:'iq',xp:30})}
 return {date:today(),mode,readiness:r,items,completed:[]};}
function ensureSmartPlan(){if(!S.smartPlan||S.smartPlan.date!==today()){S.smartPlan=buildSmartPlan();save()}return S.smartPlan}
function completeSmart(i){let p=ensureSmartPlan();if(p.completed.includes(i))return;let x=p.items[i];if(!x)return;p.completed.push(i);if(x.type==='tech')trainTechnique(x.group,x.index);else if(x.type==='cali')trainCali(x.group,x.index);else{addXP(x.xp);S.history.push({date:today(),type:'smart',name:x.title,xp:x.xp});}save();render();toast('✅ '+x.title+' مكتمل')}
function refreshSmart(){S.smartPlan=buildSmartPlan();save();render();toast('🧭 تم تحديث الخطة حسب حالتك')}
function smartView(){let p=ensureSmartPlan(),done=p.completed.length,total=p.items.length;document.getElementById('view').innerHTML=`<section class="card"><div class="eyebrow">المحرك المركزي</div><h2>🧭 خطة اليوم الذكية</h2><div class="smartgrid"><div class="scorebox"><small>الجاهزية</small><div class="readiness">${p.readiness}</div><span class="muted">/100</span></div><div class="scorebox"><small>النمط</small><div class="big">${p.mode==='hard'?'قوي':p.mode==='normal'?'طبيعي':p.mode==='light'?'خفيف':'تعافي'}</div></div><div class="scorebox"><small>المهام</small><div class="big">${done}/${total}</div></div><div class="scorebox"><small>المستوى</small><div class="big">${S.level}</div></div></div><p class="muted">الخطة تتغير تلقائياً حسب الجاهزية، نقاط الضعف، المهارات المفتوحة والإصابات المسجلة. الراحة جزء من التطور.</p><button class="btn blue" onclick="refreshSmart()">🔄 إعادة بناء الخطة</button></section><section class="section">${p.items.map((x,i)=>`<div class="planitem ${p.completed.includes(i)?'done':''}" style="margin-bottom:9px"><div class="row"><div><h3 style="margin:0">${x.icon} ${x.title}</h3><p class="muted">${x.desc}</p></div><span class="tag">+${x.xp} XP</span></div>${p.completed.includes(i)?'<b class="success">✓ مكتملة</b>':`<button class="btn primary" onclick="completeSmart(${i})">ابدأ / أكمل</button>`}</div>`).join('')}</section><section class="section grid2"><div class="card"><h3>🏆 قدرات النظام</h3><p class="muted">قوة نسبية وقوة عامة • انفجار • سرعة • تحمل هوائي ولاهوائي • حركة • توازن • قبضة • كور • مهارات ضرب وجراپلينغ • ذكاء قتالي.</p></div><div class="card"><h3>🛡️ قاعدة التقدم</h3><p class="muted">الجودة قبل السرعة، والتدرج قبل المهارات المتقدمة، ولا يوجد تدريب قسري فوق ألم أو إصابة.</p></div></section>`}
function advancedTesting(){showModal(`<h2>📏 اختبار القدرات</h2><p class="muted">اختبر فقط وأنت مرتاح وبدون ألم. الاختبار دوري وليس يومياً.</p><div class="grid2">${[['broadJump','Broad Jump cm'],['verticalJump','Vertical Jump cm'],['deadHang','Dead Hang sec'],['burpees','Burpees / 2 min'],['shuttle','Shuttle 5-10-5 sec'],['sidePlank','Side Plank sec/side']].map(([k,l])=>`<div class="field"><label>${l}</label><input id="tx_${k}" type="number" min="0" step="0.1" value="${S.testsAdvanced[k]||0}"></div>`).join('')}</div><button class="btn primary" onclick="saveAdvancedTests()">حفظ القياسات</button>`)}
function saveAdvancedTests(){Object.keys(S.testsAdvanced).forEach(k=>S.testsAdvanced[k]=+document.getElementById('tx_'+k).value||0);S.history.push({date:today(),type:'test',name:'اختبار القدرات الشامل',xp:100});addXP(100);save();closeModal();render();toast('📏 تم تحديث خط الأساس')}

// ===== V17 GAME / COMPETITION LAYER =====
const GAME_BADGES=[
 ['first','🥊','أول حصة','أكمل أول حصة تدريبية'],['streak7','🔥','7 أيام','حافظ على سلسلة 7 أيام'],['quest25','🎯','صياد المهام','أكمل 25 مهمة'],['level10','⚡','المستوى 10','وصل للمستوى 10'],['boss3','👹','قاتل الزعماء','أكمل 3 مواجهات زعيم'],['test','📏','المختبر','سجّل اختبار قدرات شامل'],['season','🏆','منافس الموسم','اجمع 1000 نقطة موسم'],['legend','👑','أسطورة','وصل للمستوى 30']
];
function seasonId(){let d=new Date(),q=Math.floor(d.getMonth()/3)+1;return `${d.getFullYear()}-S${q}`}
function weekId(){let d=new Date(),one=new Date(d.getFullYear(),0,1),n=Math.ceil((((d-one)/86400000)+one.getDay()+1)/7);return `${d.getFullYear()}-W${n}`}function weekStartDate(){let d=new Date();d.setHours(0,0,0,0);let day=(d.getDay()+6)%7;d.setDate(d.getDate()-day);return d.toISOString().slice(0,10)}
function divisionFor(r){if(!r)return 'غير مصنف';return r>=1800?'Diamond':r>=1600?'Platinum':r>=1400?'Gold':r>=1200?'Silver':'Bronze'}
function ensureGame(){
 if(!S.game)S.game=structuredClone(base.game);let sid=seasonId(),wid=weekId();
 if(S.game.seasonId!==sid){S.game.seasonId=sid;S.game.seasonPoints=0;S.game.claimed=[];S.game.daily=[];S.game.weekly=[]}
 if(S.game.weeklyStart!==wid){S.game.weeklyStart=wid;S.game.weeklyXP=0;S.game.weekly=[]}
 S.game.division=divisionFor(S.game.rating);save();
}
function trackGameXP(xp){ensureGame();let mult=eventOfDay()==='مهمة خبرة مضاعفة'?2:1;S.game.seasonPoints+=Math.max(1,Math.round(xp/4))*mult;S.game.weeklyXP+=xp;S.game.division=divisionFor(S.game.rating)}
function gameReward(kind,xp=0){ensureGame();S.game.coins+=(kind==='boss'?30:kind==='challenge'?20:10);S.game.division=divisionFor(S.game.rating);checkGameBadges();save();return xp}
function checkGameBadges(){let q=S.history.filter(x=>x.type==='quest').length,b=S.bosses?.filter(x=>x.completed).length||0;
 const got={first:S.history.some(x=>['session','technique','calisthenics','smart'].includes(x.type)),streak7:S.streak>=7,quest25:q>=25,level10:S.level>=10,boss3:b>=3,test:S.history.some(x=>x.type==='test'),season:S.game.seasonPoints>=1000,legend:S.level>=30};
 GAME_BADGES.forEach(x=>{if(got[x[0]]&&!S.game.badges.includes(x[0])){S.game.badges.push(x[0]);S.game.coins+=50;toast('🏅 شارة جديدة: '+x[1]+' '+x[2])}})
}
function dailyChallenges(){ensureGame();let d=new Date().getDay();let pool=[
 ['shadow','🥊 Shadow Fighter','أكمل مهمة Shadow/Boxing اليوم',()=>S.history.some(x=>x.date===today()&&/Shadow|Boxing/i.test(x.name||'')),100],
 ['smart','🧭 Smart Day','أكمل مهمتين من الخطة الذكية',()=>ensureSmartPlan().completed.length>=2,120],
 ['fitness','💪 Engine','سجّل تمرين لياقة أو قوة اليوم',()=>S.history.some(x=>x.date===today()&&['session','fitness','calisthenics'].includes(x.type)),100],
 ['iq','🧠 Fight IQ','أكمل مهمة ذكاء قتالي',()=>S.history.some(x=>x.date===today()&&/ذكاء|IQ/i.test(x.name||'')),90],
 ['discipline','⚔️ No Zero Day','أنجز أي مهمة تدريبية اليوم',()=>S.history.some(x=>x.date===today()),80],
 ['recovery','🫀 Recovery','سجّل تعافي/نوم اليوم',()=>S.sleep.some(x=>x.date===today()),70],
 ];
 return [pool[d%pool.length],pool[(d+2)%pool.length],pool[(d+4)%pool.length]].map(x=>({id:x[0],title:x[1],desc:x[2],done:!!x[3](),xp:x[4]}))
}
function weeklyChallenges(){let q=Math.floor(new Date().getDate()/7);return [
 {id:'wxp',title:'⚡ أسبوع الخبرة',desc:'اجمع 600 XP خلال الأسبوع',progress:Math.min(600,S.game.weeklyXP),target:600,xp:250},
 {id:'wq',title:'🎯 أسبوع المهام',desc:'أكمل 12 مهمة',progress:Math.min(12,S.history.filter(x=>x.date>=weekStartDate()).filter(x=>x.type==='quest').length),target:12,xp:300},
 {id:'wskill',title:'🌳 تطوير مهارة',desc:'ارفع أي مهارة قتالية 3 مرات',progress:Math.min(3,S.history.filter(x=>x.date>=weekStartDate()&&['technique','smart'].includes(x.type)).length),target:3,xp:220}
]}
function challengeDone(id){let d=dailyChallenges().find(x=>x.id===id);return d?.done||false}
function claimChallenge(id,weekly=false){ensureGame();let key=(weekly?'w:':'d:')+weekId()+':'+id;if(S.game.claimed.includes(key))return toast('المكافأة مأخوذة');let c=weekly?weeklyChallenges().find(x=>x.id===id):dailyChallenges().find(x=>x.id===id);if(!c)return;if(weekly?(c.progress<c.target):!c.done)return toast('كمّل التحدي أولاً');S.game.claimed.push(key);addXP(c.xp);gameReward('challenge',c.xp);toast('🎁 مكافأة التحدي +'+c.xp+' XP');render()}
async function publishLeaderboard(){if(!firebaseDb||!currentUser)return false;try{let fs=window.__mmaFS;if(!fs)return false;let ref=fs.doc(firebaseDb,'leaderboard',currentUser.uid);await fs.setDoc(ref,{uid:currentUser.uid,name:(S.name||'Fighter').slice(0,24),level:S.level,xp:S.xp,rating:S.game.rating,rank:S.rank,division:S.game.division,rankStatus:S.rankEvaluation?.status||'pending',seasonId:S.game.seasonId,seasonPoints:S.game.seasonPoints,weeklyXP:S.game.weeklyXP,badges:S.game.badges.length,updatedAt:Date.now()},{merge:true});return true}catch(e){console.warn('leaderboard publish',e);return false}}
async function loadLeaderboard(){if(!firebaseDb||!window.__mmaFS)return [];try{let fs=window.__mmaFS;let q=fs.query(fs.collection(firebaseDb,'leaderboard'),fs.orderBy('seasonPoints','desc'),fs.limit(100));let snap=await fs.getDocs(q);return snap.docs.map(x=>x.data()).filter(x=>x.seasonId===seasonId()).slice(0,50)}catch(e){console.warn('leaderboard load',e);return []}}
async function refreshLeaderboard(){let box=document.getElementById('lb');if(!box)return;box.innerHTML='<div class="empty">⏳ عم حمّل الترتيب...</div>';let rows=await loadLeaderboard();if(!rows.length){box.innerHTML='<div class="empty">الترتيب العالمي يظهر بعد تفعيل Firebase وتسجيل لاعبين.</div>';return}box.innerHTML=rows.map((r,i)=>`<div class="leaderrow ${currentUser&&r.uid===currentUser.uid?'me':''}"><div class="pos">#${i+1}</div><div><b>${escapeHtml(r.name||'Fighter')}</b><div class="muted">Lv.${r.level||1} • ${r.division||'غير مصنف'} • ${r.rating||0} Rating • ${r.rank||'غير مصنف'}</div></div><strong>${r.seasonPoints||0} SP</strong></div>`).join('')}
async function arena(){ensureGame();checkGameBadges();let ds=dailyChallenges(),ws=weeklyChallenges();let pct=Math.min(100,Math.round((S.game.seasonPoints/1000)*100));let badges=S.game.badges.map(id=>GAME_BADGES.find(x=>x[0]===id)).filter(Boolean);document.getElementById('view').innerHTML=`<section class="card gamehero"><div class="eyebrow">MMA ARENA • ${S.game.seasonId}</div><div class="row"><div><h1>🏆 ساحة المقاتلين</h1><p class="muted">تحديات حركات وشادو بوكس • موسم • ترتيب نقاط • شارات • الرانك القتالي يعتمد على AI</p></div><span class="division">${S.game.division}</span></div><div class="gamegrid"><div class="scorebox"><small>Rating</small><div class="gameStat">${S.game.rating}</div></div><div class="scorebox"><small>نقاط الموسم</small><div class="gameStat">${S.game.seasonPoints}</div></div><div class="scorebox"><small>Coins</small><div class="gameStat">🪙 ${S.game.coins}</div></div><div class="scorebox"><small>هذا الأسبوع</small><div class="gameStat">${S.game.weeklyXP} XP</div></div></div><div class="seasonbar"><i style="width:${pct}%"></i></div><small class="muted">نقاط الموسم للعبة والتحديات. أما الرانك القتالي فلا يتغير من النقاط؛ لا يُمنح إلا بعد تحليل فيديو بالذكاء الاصطناعي.</small></section>
<section class="section grid2"><div class="card"><div class="row"><h2>⚔️ تحديات اليوم</h2><span class="tag">تتجدد يومياً</span></div>${ds.map(c=>{let key='d:'+weekId()+':'+c.id,claimed=S.game.claimed.includes(key);return `<div class="challenge ${c.done?'done':''}" style="margin-top:8px"><div class="row"><div><b>${c.title}</b><div class="muted">${c.desc}</div></div><span class="tag">+${c.xp} XP</span></div><button class="btn ${c.done?'green':''}" style="margin-top:8px" onclick="claimChallenge('${c.id}')">${claimed?'✓ مأخوذة':c.done?'🎁 استلم المكافأة':'🔒 أكمل التحدي'}</button></div>`}).join('')}</div>
<div class="card"><div class="row"><h2>📅 تحديات الأسبوع</h2><span class="tag">${S.game.weeklyXP} XP</span></div>${ws.map(c=>{let key='w:'+weekId()+':'+c.id,claimed=S.game.claimed.includes(key);return `<div class="challenge" style="margin-top:8px"><b>${c.title}</b><div class="muted">${c.desc}</div><div class="bar" style="margin:8px 0"><i style="width:${Math.min(100,c.progress/c.target*100)}%"></i></div><div class="row"><small>${c.progress}/${c.target}</small><button class="btn gold" onclick="claimChallenge('${c.id}',true)">${claimed?'✓':c.progress>=c.target?'🎁':'🔒'}</button></div></div>`}).join('')}</div></section>
<section class="section grid2"><div class="card"><div class="row"><h2>🌍 الترتيب العالمي</h2><button class="btn" onclick="refreshLeaderboard()">↻</button></div><div id="lb"><div class="empty">اضغط تحديث لعرض ترتيب الموسم.</div></div><button class="btn blue" onclick="publishLeaderboard().then(()=>refreshLeaderboard())">☁️ تحديث مركزي</button></div><div class="card"><h2>🏅 مجموعتي</h2><p class="muted">الشارات التي جمعتها:</p><div style="display:flex;gap:6px;flex-wrap:wrap">${badges.length?badges.map(b=>`<span class="badge">${b[1]} ${b[2]}</span>`).join(''):'<span class="muted">ابدأ أول تحدي لتحصل على أول شارة.</span>'}</div><hr style="border-color:var(--line);margin:14px 0"><p class="muted">السبارينغ للتطور والتحليل، وليس لرفع الترتيب بمجرد إدخال فوز ذاتي. الـRating التنافسي يبقى منفصلاً عن السجل التدريبي.</p><button class="btn primary" onclick="arenaMatchModal()">🥋 تسجيل سبارينغ</button></div></section>`}
function arenaMatchModal(){showModal(`<h2>🥋 تسجيل سبارينغ</h2><p class="muted">سجّل الجولة لتحليل تقدمك. هذا السجل لا يغيّر Rating التنافسي.</p><div class="grid3"><div class="field"><label>الجولات</label><input id="amr" type="number" min="1" value="3"></div><div class="field"><label>مدة الجولة بالدقائق</label><input id="amm" type="number" min="1" value="3"></div><div class="field"><label>الشدة 1–10</label><input id="ami" type="number" min="1" max="10" value="6"></div></div><div class="grid2"><div class="field"><label>شو نجح؟</label><textarea id="amgood" placeholder="مثلاً: الجاب والدفاع"></textarea></div><div class="field"><label>شو يحتاج تطوير؟</label><textarea id="ambad" placeholder="مثلاً: الدفاع ضد الإسقاط"></textarea></div></div><button class="btn primary" onclick="recordArenaMatch()">حفظ السبارينغ</button>`)}
function recordArenaMatch(){let rounds=Math.max(1,+document.getElementById('amr').value||3),minutes=Math.max(1,+document.getElementById('amm').value||3),intensity=Math.max(1,Math.min(10,+document.getElementById('ami').value||6)),good=document.getElementById('amgood').value.trim(),bad=document.getElementById('ambad').value.trim();let xp=Math.min(180,40+rounds*12);S.sparring.push({date:today(),rounds,minutes,intensity,good,bad,source:'arena_log'});S.history.push({date:today(),type:'sparring',name:'Arena Sparring',xp});addXP(xp);gameReward('challenge',xp);save();closeModal();render();toast('🥋 تم حفظ السبارينغ +'+xp+' XP')}

function updateNetworkStatus(){const el=document.getElementById('netStatus');if(!el)return;const online=navigator.onLine;el.textContent=online?'● متصل':'○ بدون إنترنت';el.style.color=online?'var(--green)':'var(--warn)'}
window.addEventListener('online',()=>{updateNetworkStatus();toast('🌐 عاد الاتصال');if(currentUser&&firebaseDb)cloudSave(firebaseDb,currentUser.uid)});window.addEventListener('offline',()=>{updateNetworkStatus();toast('📴 وضع عدم الاتصال — تقدمك محفوظ محلياً')});
function render(){updateNetworkStatus();document.getElementById('streak').textContent='🔥 '+S.streak;if(!S.profileComplete){document.getElementById('nav').innerHTML='';document.getElementById('view').innerHTML='<section class="card" style="margin-top:40px;text-align:center"><div class="eyebrow">MMA SYSTEM</div><h1>🥊 ابنِ مقاتلك من الصفر</h1><p class="muted">لا اسم جاهز، لا Rating، لا Rank. ابدأ ببياناتك ثم طوّر مهاراتك.</p><button class="btn primary" onclick="openOnboarding()">🚀 إنشاء ملف المقاتل</button></section>';return}nav();document.getElementById('authBtn').textContent=currentUser?(currentUser.displayName||'Google ✓'):t('login');document.getElementById('authBtn').textContent=currentUser?(currentUser.displayName||'Google ✓'):t('login');document.getElementById('installBtn')?.classList.toggle('hidden',!installPrompt);if(tab==='home')home();if(tab==='arena')arena();if(tab==='smart')smartView();if(tab==='training')training();if(tab==='calisthenics')caliView();if(tab==='fitness')fitnessView();if(tab==='skills')skills();if(tab==='stats')stats();if(tab==='sparring')sparring();if(tab==='progress')progress();if(tab==='camp')camp();if(tab==='nutrition')nutrition();if(tab==='recovery')recovery();if(tab==='ai')ai();if(tab==='profile')profile()}
async function initAuth(){if(!S.settings.firebase)return;try{const appmod=await import('https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js');const authmod=await import('https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js');const fs=await import('https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js');firebaseFs=fs;window.__mmaFS=fs;if(!firebaseApp){firebaseApp=appmod.initializeApp(S.settings.firebase,'mma-project-s');firebaseAuth=authmod.getAuth(firebaseApp);firebaseDb=fs.getFirestore(firebaseApp);}authmod.onAuthStateChanged(firebaseAuth,async u=>{currentUser=u;if(u){S.name=u.displayName||S.name;S.settings.cloud=true;await cloudLoadOrCreate(fs,u.uid);}else{S.settings.cloud=false;}save();render()})}catch(e){console.warn('تهيئة Firebase',e)}}
window.addEventListener('load',async()=>{document.documentElement.lang='ar';document.documentElement.dir='rtl';render();if(!S.profileComplete)setTimeout(openOnboarding,250);else generate();if('serviceWorker' in navigator){try{await navigator.serviceWorker.register('sw.js')}catch(e){}}await initAuth()});
